### ISSUE TITLE
Unhandled exception: System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container'

### ISSUE THREAD

**Issue by Kgriffin314** [RenanYudi/DiscordChatExporter-Unix#1]
could not export because of unfixable error
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 

I tried installing stylet but is incompatible with linux , using nuget yield the dreaded 'Unable to find package' 

Please help me and fix this problem! 

Thank you

**Comment by RenanYudi** [comment]
Script will be rewritten when I have time.
Issue solved [here](https://github.com/Tyrrrz/DiscordChatExporter/issues/210).
